// Emits the two stylesheets the web apps import. Run with plain `node` — Node 24
// strips the types, so there is no build step in front of the build step.
//
//   dist/tokens.css   the custom properties, one set per colour scheme
//   dist/tailwind.css the @theme block that turns them into utility classes
//
// The second file is generated rather than hand-written so that adding a
// semantic token to tokens.json is all it takes to get `bg-<token>` — a list
// maintained by hand drifts the moment someone is in a hurry.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { flatten, tokens } from '../src/resolve.ts';

const PREFIX = 'he';
const outDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'dist');

const scales = {
  font: tokens.font,
  space: tokens.space,
  radius: tokens.radius,
  elevation: tokens.elevation,
  motion: tokens.motion,
  breakpoint: tokens.breakpoint,
};

const declarations = (group: Record<string, string>, indent: string) =>
  Object.entries(group)
    .map(([name, value]) => `${indent}--${PREFIX}-${name}: ${value};`)
    .join('\n');

const mapped = (entries: Array<[string, string]>, indent: string) =>
  entries.map(([name, source]) => `${indent}--${name}: var(--${PREFIX}-${source});`).join('\n');

const tokensCss = `/* GENERATED by packages/tokens — edit src/tokens.json, then run \`pnpm tokens:build\`. */

:root {
  color-scheme: light dark;

  /* Semantic colour — light */
${declarations(flatten(tokens.semantic.light), '  ')}

  /* Scales — identical in both schemes */
${declarations(flatten(scales), '  ')}
}

/* With no explicit choice recorded, follow the operating system. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${declarations(flatten(tokens.semantic.dark), '    ')}
  }
}

/* An explicit choice wins over the system preference, in both directions. */
:root[data-theme='dark'] {
${declarations(flatten(tokens.semantic.dark), '  ')}
}

:root[data-theme='light'] {
${declarations(flatten(tokens.semantic.light), '  ')}
}
`;

// Only semantic colour names become utilities. Reaching for a raw ramp step in
// a component is how a palette stops being changeable, so the ramps stay put.
const semanticColors = Object.keys(flatten(tokens.semantic.light)).map(
  (name) => [`color-${name}`, name] as [string, string],
);

const themeCss = `/* GENERATED by packages/tokens — edit src/tokens.json, then run \`pnpm tokens:build\`. */

/*
 * \`inline\` keeps Tailwind emitting \`var(--he-*)\` rather than the resolved value,
 * so a utility class follows the active colour scheme instead of freezing the
 * light value at build time.
 */
@theme inline {
${mapped(semanticColors, '  ')}

${mapped(
  [
    ['font-sans', 'font-family-sans'],
    ['font-mono', 'font-family-mono'],
  ],
  '  ',
)}

${mapped(
  Object.keys(tokens.font.size).map((n) => [`text-${n}`, `font-size-${n}`] as [string, string]),
  '  ',
)}

${mapped(
  Object.keys(tokens.font.weight).map(
    (n) => [`font-weight-${n}`, `font-weight-${n}`] as [string, string],
  ),
  '  ',
)}

${mapped(
  Object.keys(tokens.radius).map((n) => [`radius-${n}`, `radius-${n}`] as [string, string]),
  '  ',
)}

${mapped(
  Object.keys(tokens.elevation)
    .filter((n) => n !== 'none')
    .map((n) => [`shadow-${n}`, `elevation-${n}`] as [string, string]),
  '  ',
)}

${mapped(
  Object.keys(tokens.motion.duration).map(
    (n) => [`duration-${n}`, `motion-duration-${n}`] as [string, string],
  ),
  '  ',
)}

${mapped(
  Object.keys(tokens.motion.easing).map(
    (n) => [`ease-${n}`, `motion-easing-${n}`] as [string, string],
  ),
  '  ',
)}

  /* A media query cannot read a custom property, so breakpoints are the one
     group that has to be inlined as literals. */
${Object.entries(tokens.breakpoint)
  .map(([name, value]) => `  --breakpoint-${name}: ${value};`)
  .join('\n')}
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'tokens.css'), tokensCss, 'utf8');
writeFileSync(join(outDir, 'tailwind.css'), themeCss, 'utf8');
console.log('tokens: wrote dist/tokens.css and dist/tailwind.css');
