import type { AdminWorker } from './types.ts';

/**
 * Rows for the screen to be built and swept against, until the admin API exists.
 *
 * A fixture as an *input*, which is what §1.6 allows: the list, the filters and
 * the paging are real code running over it, and the moment the endpoint lands
 * this module is the only thing that is replaced. Nothing here stands in for a
 * boundary a check is meant to prove.
 *
 * The people are invented and the addresses are in the United States and Canada,
 * because that is where the employers paying for this are — an admin screen
 * whose sample data is from somewhere else reads as somebody else's product.
 * Two rows are deliberately awkward: one country with no state at all, and one
 * name long enough to find the column that refuses to shrink.
 */
export const SAMPLE_WORKERS: AdminWorker[] = [
  {
    id: 3,
    name: 'Marcus Delgado',
    email: 'marcus.delgado@example.com',
    country: 'United States',
    state: 'California',
    status: 'completed',
    flag: 'flagged',
    joinedOn: '2026-01-14',
  },
  {
    id: 6,
    name: 'Priya Raghunathan-Whitfield',
    email: 'priya.raghunathan.whitfield@example.com',
    country: 'United States',
    state: 'New York',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-02-02',
  },
  {
    id: 8,
    name: 'Danielle Okafor',
    email: 'danielle.okafor@example.com',
    country: 'United States',
    state: 'Georgia',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-02-19',
  },
  {
    id: 10,
    name: 'Ethan Brooks',
    email: 'ethan.brooks@example.com',
    country: 'United States',
    state: 'Texas',
    status: 'not_completed',
    flag: 'not_flagged',
    joinedOn: '2026-03-03',
  },
  {
    id: 12,
    name: 'Amara Nwosu',
    email: 'amara.nwosu@example.com',
    country: 'Canada',
    state: 'Ontario',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-03-11',
  },
  {
    id: 13,
    name: 'Julian Reyes',
    email: 'julian.reyes@example.com',
    country: 'United States',
    state: 'Arizona',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-03-27',
  },
  {
    id: 14,
    name: 'Hannah Lindqvist',
    email: 'hannah.lindqvist@example.com',
    country: 'Canada',
    state: 'British Columbia',
    status: 'not_completed',
    flag: 'flagged',
    joinedOn: '2026-04-08',
  },
  {
    id: 16,
    name: 'Tomás Villanueva',
    email: 'tomas.villanueva@example.com',
    country: 'United States',
    state: 'Illinois',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-04-22',
  },
  {
    id: 17,
    name: 'Grace Ferreira',
    email: 'grace.ferreira@example.com',
    country: 'Singapore',
    state: null,
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-05-06',
  },
  {
    id: 18,
    name: 'Noah Whitfield',
    email: 'noah.whitfield@example.com',
    country: 'United States',
    state: 'Maine',
    status: 'not_completed',
    flag: 'not_flagged',
    joinedOn: '2026-05-18',
  },
  {
    id: 21,
    name: 'Leila Haddad',
    email: 'leila.haddad@example.com',
    country: 'Canada',
    state: 'Quebec',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-06-01',
  },
  {
    id: 24,
    name: 'Samuel Adeyemi',
    email: 'samuel.adeyemi@example.com',
    country: 'United States',
    state: 'Washington',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-06-15',
  },
  {
    id: 27,
    name: 'Chloe Bernard',
    email: 'chloe.bernard@example.com',
    country: 'United States',
    state: 'Florida',
    status: 'not_completed',
    flag: 'flagged',
    joinedOn: '2026-07-04',
  },
  {
    id: 31,
    name: 'Ravi Chandrasekaran',
    email: 'ravi.chandrasekaran@example.com',
    country: 'Canada',
    state: 'Alberta',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-07-29',
  },
  {
    id: 34,
    name: 'Isabelle Moreau',
    email: 'isabelle.moreau@example.com',
    country: 'United States',
    state: 'Colorado',
    status: 'completed',
    flag: 'not_flagged',
    joinedOn: '2026-08-12',
  },
  {
    id: 37,
    name: 'Owen Kirk',
    email: 'owen.kirk@example.com',
    country: 'Singapore',
    state: null,
    status: 'not_completed',
    flag: 'not_flagged',
    joinedOn: '2026-08-30',
  },
];
