/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/username-available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check whether a username is free
         * @description Public because a username is a public identifier — confirming one is taken reveals nothing a profile page would not. Rate limited, because an instant public answer is also a way to harvest the handles in use.
         */
        get: operations["RegistrationController_usernameAvailable_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates no account. The sign-up waits, and a six-digit code is emailed to the address; the account is created only when that code is confirmed. Answers 202 whether or not the address already has an account, so the endpoint cannot be used to discover which addresses do — the owner of an existing account is told by email instead. Signing up again at an address that is still waiting replaces the waiting details and sends a new code. A taken username answers 409, including one held by a sign-up still waiting for confirmation.
         */
        post: operations["RegistrationController_register_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a fresh confirmation code
         * @description Answers 202 for an unknown address, an existing account and a waiting sign-up alike. Only a sign-up still waiting is sent a code, and the new code replaces the previous one.
         */
        post: operations["RegistrationController_resendVerification_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm the address and create the account
         * @description Creates the account from the waiting sign-up. Wrong, expired and unknown all answer the same 400, and five wrong guesses retire the code. Does not sign the person in: they sign in with their email address and password, which keeps a forwarded code from becoming a session. Limited per address as well as per IP, so rotating IPs buys no extra guesses.
         */
        post: operations["RegistrationController_verifyEmail_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for an access and refresh token */
        post: operations["SessionController_login_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token
         * @description Reads the token from the httpOnly cookie for browsers, or from the body for native clients. Presenting a token that has already been rotated revokes every session in its family, because a replay cannot be told apart from a theft.
         */
        post: operations["SessionController_refresh_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session and its rotation family */
        post: operations["SessionController_logout_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller’s active sessions */
        get: operations["SessionController_listSessions_v1"];
        put?: never;
        post?: never;
        /** Sign out everywhere else, keeping this session */
        delete: operations["SessionController_revokeOtherSessions_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke one of the caller’s sessions
         * @description Ownership is enforced in the query, not assumed from the permission: without that filter, knowing another user’s session id would be enough to sign them out.
         */
        delete: operations["SessionController_revokeSession_v1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start password recovery
         * @description Emails a six-digit recovery code. An address whose sign-up was never confirmed has no password to reset, and is sent a reminder to sign up again instead. Answers 202 for every address, known or not: a reset endpoint that only responds for real accounts is a membership oracle that needs no password to query.
         */
        post: operations["PasswordController_forgot_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a recovery code for a reset grant
         * @description Returns a single-use token, valid for ten minutes, that `reset` accepts. Wrong, expired and unknown all answer the same 400. Limited per address as well as per IP, because the code belongs to an account and the guessing budget has to be spent per account too.
         */
        post: operations["PasswordController_verifyCode_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete a password reset
         * @description Ends every existing session. Someone resetting a password is often doing it because they believe the account is compromised; leaving the attacker signed in would defeat the exercise.
         */
        post: operations["PasswordController_reset_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password of the signed-in user
         * @description Requires the current password. Ends every session on every device, including this one, and returns a fresh token pair so the caller stays signed in where they are.
         */
        post: operations["PasswordController_change_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user, their roles and their permissions
         * @description Clients render from permissions rather than roles, so a grant change needs no client release. The server re-checks every permission regardless — this list draws the interface, it does not decide access.
         */
        get: operations["AccountController_me_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public keys for verifying access tokens */
        get: operations["JwksController_jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the caller’s profile draft
         * @description One profile per account. A second attempt — including several sent at once — answers 409 with code CONFLICT.
         */
        post: operations["ProfilesController_create_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller’s own profile, including contact details
         * @description The only response shape that carries the contact object. There is no route that returns it by id or slug, so guessing an identifier does not reach it. Answers 404 until the profile has been created.
         */
        get: operations["ProfilesController_getOwn_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Autosave the profile draft
         * @description Every request states the version it was editing. A mismatch answers 409 with code VERSION_CONFLICT and `details.currentVersion`, so the client can offer a reload — a later edit is never silently overwritten. A field sent as null is cleared; a field left out is kept.
         */
        patch: operations["ProfilesController_update_v1"];
        trace?: never;
    };
    "/api/v1/profiles/me/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set what the profile shows publicly
         * @description Location granularity narrows rather than relabels: choosing country drops the city entirely rather than hiding its label.
         */
        put: operations["ProfilesController_updateVisibility_v1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish the profile
         * @description Applies a stricter schema than autosave; failures answer 400 with one issue per field. Publishing a profile that is already published changes nothing and answers 200. An edit landing at the same moment answers 409 VERSION_CONFLICT.
         */
        post: operations["ProfilesController_publish_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw the profile from public view
         * @description Withdrawing a profile that is not published changes nothing and answers 200. An edit landing at the same moment answers 409 VERSION_CONFLICT.
         */
        post: operations["ProfilesController_unpublish_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history of the caller’s profile */
        get: operations["ProfilesController_listRevisions_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/me/avatar-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * A signed upload for the caller’s profile photo
         * @description The bytes go straight to storage, never through this API (ADR-004). Post the returned fields and the file to the returned URL, then claim the key with a normal PATCH of the profile. The signature states the key, the type and a size range, so storage refuses anything else.
         */
        post: operations["ProfilesController_avatarUpload_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profiles/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A published public profile
         * @description Answers 404 for a draft, a suspended profile, one switched to private, and a slug that never existed — identically. A 403 would confirm the profile is real and merely hidden.
         */
        get: operations["ProfilesController_getPublic_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The approved skills a profile may claim
         * @description Public because the list is what a profile form offers and what a buyer filters by; nothing here belongs to anyone.
         */
        get: operations["TaxonomyController_list_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a skill the taxonomy does not have
         * @description Answers 202: the skill is recorded for review, not added. Suggesting the same skill again is the same request and answers the same way.
         */
        post: operations["TaxonomyController_suggest_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorBody: {
            /**
             * @description Stable machine-readable code
             * @example VALIDATION_FAILED
             */
            code: string;
            /** @example Request validation failed */
            message: string;
            details?: {
                [key: string]: unknown;
            };
            /** @example 01JAV6M0T6M4T6QK1K7C0X5R2Z */
            requestId: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        AuthenticatedUser: {
            id: string;
            email: string;
            firstName: string | null;
            lastName: string | null;
            username: string | null;
            status: string;
            emailVerified: boolean;
            roles: string[];
            permissions: string[];
        };
        RequestPasswordReset: {
            email: string;
        };
        Accepted: {
            /** @constant */
            accepted: true;
        };
        VerifyResetCodeRequest: {
            email: string;
            code: string;
        };
        ResetCodeVerified: {
            resetToken: string;
            expiresInSeconds: number;
        };
        ResetPasswordRequest: {
            token: string;
            password: string & (string);
        };
        PasswordResetCompleted: {
            /** @constant */
            reset: true;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string & (string);
        };
        AuthTokensResponse: {
            accessToken: string;
            expiresIn: number;
            refreshToken?: string;
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                username: string | null;
                status: string;
                emailVerified: boolean;
                roles: string[];
                permissions: string[];
            };
        };
        UsernameAvailabilityResponse: {
            username: string;
            available: boolean;
        };
        RegisterRequest: {
            firstName: string;
            lastName: string;
            username: string;
            email: string;
            password: string & (string);
            confirmPassword: string;
        };
        ResendVerificationRequest: {
            email: string;
        };
        VerifyEmailRequest: {
            email: string;
            code: string;
        };
        VerifyEmailResponse: {
            /** @constant */
            verified: true;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        RefreshRequest: {
            refreshToken?: string;
        };
        Revoked: {
            /** @constant */
            revoked: true;
        };
        SessionListResponse: {
            id: string;
            current: boolean;
            userAgent: string | null;
            devicePlatform: string | null;
            deviceModel: string | null;
            issuedAt: string;
            expiresAt: string;
        }[];
        SkillListResponse: {
            skills: {
                slug: string;
                name: string;
                category: string | null;
            }[];
        };
        SuggestSkillRequest: {
            name: string;
        };
        SkillSuggestionResponse: {
            slug: string;
            name: string;
            /** @enum {string} */
            status: "pending" | "accepted" | "declined";
        };
        ProfileConflictDetails: {
            currentVersion: number;
            yourVersion: number;
        };
        OwnProfileResponse: {
            id: string;
            slug: string;
            /** @enum {string} */
            status: "draft" | "published" | "suspended";
            version: number;
            completeness: number;
            displayName: string | null;
            avatarUrl: string | null;
            headline: string | null;
            overview: string | null;
            videoIntroUrl: string | null;
            locationCountry: string | null;
            locationRegion: string | null;
            locationCity: string | null;
            serviceArea: string | null;
            timezone: string | null;
            remoteMode: ("remote" | "on_site" | "hybrid") | null;
            availability: ("available" | "open_to_offers" | "unavailable") | null;
            availabilityNote: string | null;
            rateAmountMinor: string | null;
            ratePeriod: ("weekly" | "monthly" | "yearly") | null;
            rateCurrency: string;
            contact: {
                phoneE164: string | null;
                contactEmail: string | null;
                addressLine1: string | null;
                addressLine2: string | null;
                postalCode: string | null;
                dateOfBirth: string | null;
            };
            sections: {
                languages: {
                    name: string;
                    proficiency: ("basic" | "conversational" | "fluent" | "native") | null;
                }[];
                skills: {
                    name: string;
                    proficiency: ("beginner" | "intermediate" | "advanced" | "expert") | null;
                    years: number | null;
                    approved: boolean;
                }[];
                experience: {
                    role: string;
                    organization: string | null;
                    startDate: string | null;
                    endDate: string | null;
                    summary: string | null;
                }[];
                education: {
                    institution: string;
                    qualification: string | null;
                    fieldOfStudy: string | null;
                    startDate: string | null;
                    endDate: string | null;
                }[];
                licenses: {
                    name: string;
                    issuer: string | null;
                    issuedOn: string | null;
                    expiresOn: string | null;
                }[];
                portfolio: {
                    title: string;
                    url: string | null;
                    summary: string | null;
                }[];
            };
            visibility: {
                profilePublic: boolean;
                /** @enum {string} */
                locationGranularity: "hidden" | "country" | "region" | "city";
                sections: {
                    nameHeadline: boolean;
                    biography: boolean;
                    location: boolean;
                    languages: boolean;
                    rate: boolean;
                    skills: boolean;
                    experience: boolean;
                    education: boolean;
                    licenses: boolean;
                    portfolio: boolean;
                    videoIntro: boolean;
                    availability: boolean;
                };
                searchIndexable: boolean;
            };
            publishedAt: string | null;
            updatedAt: string;
        };
        UpdateProfileRequest: {
            version: number;
            profile?: {
                displayName?: string | null;
                avatarKey?: string | null;
                headline?: string | null;
                overview?: string | null;
                videoIntroUrl?: string | null;
                locationCountry?: string | null;
                locationRegion?: string | null;
                locationCity?: string | null;
                serviceArea?: string | null;
                timezone?: string | null;
                remoteMode?: ("remote" | "on_site" | "hybrid") | null;
                /** @enum {string} */
                availability?: "available" | "open_to_offers" | "unavailable";
                availabilityNote?: string | null;
                rateAmountMinor?: string | null;
                ratePeriod?: ("weekly" | "monthly" | "yearly") | null;
            };
            contact?: {
                phoneE164?: string | null;
                contactEmail?: string | null;
                addressLine1?: string | null;
                addressLine2?: string | null;
                postalCode?: string | null;
                dateOfBirth?: string | null;
            };
            sections?: {
                languages?: {
                    name: string;
                    proficiency?: ("basic" | "conversational" | "fluent" | "native") | null;
                }[];
                skills?: {
                    name: string;
                    proficiency?: ("beginner" | "intermediate" | "advanced" | "expert") | null;
                    years?: number | null;
                }[];
                experience?: {
                    role: string;
                    organization?: string | null;
                    startDate?: string | null;
                    endDate?: string | null;
                    summary?: string | null;
                }[];
                education?: {
                    institution: string;
                    qualification?: string | null;
                    fieldOfStudy?: string | null;
                    startDate?: string | null;
                    endDate?: string | null;
                }[];
                licenses?: {
                    name: string;
                    issuer?: string | null;
                    issuedOn?: string | null;
                    expiresOn?: string | null;
                }[];
                portfolio?: {
                    title: string;
                    url?: string | null;
                    summary?: string | null;
                }[];
            };
        };
        UpdateVisibilityRequest: {
            version: number;
            profilePublic: boolean;
            /** @enum {string} */
            locationGranularity: "hidden" | "country" | "region" | "city";
            sections: {
                nameHeadline: boolean;
                biography: boolean;
                location: boolean;
                languages: boolean;
                rate: boolean;
                skills: boolean;
                experience: boolean;
                education: boolean;
                licenses: boolean;
                portfolio: boolean;
                videoIntro: boolean;
                availability: boolean;
            };
            searchIndexable: boolean;
        };
        ProfileVisibilityResponse: {
            profilePublic: boolean;
            /** @enum {string} */
            locationGranularity: "hidden" | "country" | "region" | "city";
            sections: {
                nameHeadline: boolean;
                biography: boolean;
                location: boolean;
                languages: boolean;
                rate: boolean;
                skills: boolean;
                experience: boolean;
                education: boolean;
                licenses: boolean;
                portfolio: boolean;
                videoIntro: boolean;
                availability: boolean;
            };
            searchIndexable: boolean;
        };
        ProfileRevisionList: {
            version: number;
            changedAt: string;
            changeReason: string | null;
        }[];
        AvatarUploadRequest: {
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
        };
        UploadTicket: {
            url: string;
            fields: {
                [key: string]: string;
            };
            key: string;
            expiresAt: string;
            maxBytes: number;
        };
        PublicProfileResponse: {
            slug: string;
            displayName: string | null;
            avatarUrl: string | null;
            headline: string | null;
            overview: string | null;
            location: string | null;
            availability: ("available" | "open_to_offers" | "unavailable") | null;
            availabilityNote: string | null;
            rate: {
                currency: string;
                amountMinor: string;
                /** @enum {string} */
                period: "weekly" | "monthly" | "yearly";
            } | null;
            languages: {
                name: string;
                proficiency: string | null;
            }[];
            skills: {
                name: string;
                proficiency: string | null;
            }[];
            experience: {
                role: string;
                organization: string | null;
                startDate: string | null;
                endDate: string | null;
                summary: string | null;
            }[];
            education: {
                institution: string;
                qualification: string | null;
                fieldOfStudy: string | null;
                startDate: string | null;
                endDate: string | null;
            }[];
            licenses: {
                name: string;
                issuer: string | null;
                issuedOn: string | null;
                expiresOn: string | null;
            }[];
            portfolio: {
                title: string;
                url: string | null;
                summary: string | null;
            }[];
            videoIntroUrl: string | null;
            searchIndexable: boolean;
            publishedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description All checked dependencies are reachable
             *
             *     The Health Check is successful
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example ok
                         * @enum {string}
                         */
                        status?: "ok" | "degraded";
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /** @example {} */
                        error?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
            /** @description The Health Check is not successful */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @example error
                         * @enum {string}
                         */
                        status?: "error" | "shutting_down";
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       }
                         *     }
                         */
                        info?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        error?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        } | null;
                        /**
                         * @example {
                         *       "database": {
                         *         "status": "up",
                         *         "responseTime": 12
                         *       },
                         *       "redis": {
                         *         "status": "down",
                         *         "message": "Could not connect",
                         *         "responseTime": 3005
                         *       }
                         *     }
                         */
                        details?: {
                            [key: string]: {
                                /** @enum {string} */
                                status: "up" | "degraded" | "down";
                                /** @description Time the health indicator took to respond, in ms */
                                responseTime?: number;
                            } & {
                                [key: string]: unknown;
                            };
                        };
                    };
                };
            };
        };
    };
    RegistrationController_usernameAvailable_v1: {
        parameters: {
            query: {
                username: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsernameAvailabilityResponse"];
                };
            };
        };
    };
    RegistrationController_register_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    RegistrationController_resendVerification_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendVerificationRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    RegistrationController_verifyEmail_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyEmailResponse"];
                };
            };
        };
    };
    SessionController_login_v1: {
        parameters: {
            query?: never;
            header?: {
                "X-Device-Model"?: string;
                /** @description Client-generated device id */
                "X-Device-Id"?: string;
                /** @description web (default), ios or android. Browsers receive the refresh token as an httpOnly cookie and no token in the body; native clients receive it in the body. */
                "X-Client-Platform"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
        };
    };
    SessionController_refresh_v1: {
        parameters: {
            query?: never;
            header?: {
                /** @description web (default), ios or android. Browsers receive the refresh token as an httpOnly cookie and no token in the body; native clients receive it in the body. */
                "X-Client-Platform"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
        };
    };
    SessionController_logout_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revoked"];
                };
            };
        };
    };
    SessionController_listSessions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    SessionController_revokeOtherSessions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionController_revokeSession_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PasswordController_forgot_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordReset"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    PasswordController_verifyCode_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyResetCodeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetCodeVerified"];
                };
            };
        };
    };
    PasswordController_reset_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetCompleted"];
                };
            };
        };
    };
    PasswordController_change_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokensResponse"];
                };
            };
        };
    };
    AccountController_me_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    JwksController_jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProfilesController_create_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnProfileResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicts with the current state; see `error.code` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_getOwn_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnProfileResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_update_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Saved; carries the new version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnProfileResponse"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicts with the current state; see `error.code` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_updateVisibility_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVisibilityRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileVisibilityResponse"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicts with the current state; see `error.code` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_publish_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnProfileResponse"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicts with the current state; see `error.code` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_unpublish_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnProfileResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflicts with the current state; see `error.code` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_listRevisions_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRevisionList"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_avatarUpload_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvatarUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadTicket"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ProfilesController_getPublic_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Opaque public profile slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfileResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaxonomyController_list_v1: {
        parameters: {
            query?: {
                /** @description Up to 100, 50 by default */
                limit?: unknown;
                /** @description Matches anywhere in the name */
                query?: unknown;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TaxonomyController_suggest_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestSkillRequest"];
            };
        };
        responses: {
            /** @description Recorded */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSuggestionResponse"];
                };
            };
            /** @description The request failed validation; `details.issues` names each field */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not signed in */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Signed in without the permission this needs */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
